### ISSUE TITLE
[REQ] Music Commands

### ISSUE THREAD

**Issue by cthpw103** [smolespi/Hibiki#1]
Perhaps implementing the old music commands would be something to explore? Use the Discogs & MusicBrainz API?

**Comment by espimarisa** [comment]
We've considered it & I'll look into it more in the future, depending on how well their APIs are.

**Comment by cthpw103** [comment]
Perhaps using more APIs (Bandcamp, Soundcloud, YouTube etc...) **could** be useful. Not sure how good the YouTube API is at giving Music metadata although

**Comment by espimarisa** [comment]
I don't think the YouTube API returns song info by default (maybe they do on their auto-genned things [like these](https://www.youtube.com/watch?v=8kIcRg9yfg4) but I'll have to check. Other APIs would be useful to have for metadata + playback aswell.

**Comment by cthpw103** [comment]
https://developers.google.com/youtube/v3/docs/videos#resource

Doesn't seem to have much information relating to songs.

**Comment by cthpw103** [comment]
_maybe_ we _could_ tell if it's an official upload via contentDetails.licensedContent, doubt it'll be of use

**Comment by espimarisa** [comment]
Figured it didn't; that's where the other APIs like MusicBrainz or Discogs could come into play.. maybe also for album covers etc. I'll look thru what the API actually returns soon though

**Comment by cthpw103** [comment]
How may we tell the song title and artist name without doing some stuff to the video title?

**Comment by espimarisa** [comment]
We could figure something hacky out if there's not a proper way to do it

**Comment by cthpw103** [comment]
¯\\_(ツ)\_/¯

**Comment by ghost** [comment]
[rovi](http://developer.rovicorp.com/docs) has a good api

**Comment by alecks** [comment]
> I don't think the YouTube API returns song info by default (maybe they do on their auto-genned things [like these](https://www.youtube.com/watch?v=8kIcRg9yfg4) but I'll have to check. Other APIs would be useful to have for metadata + playback aswell.

Assuming that you want to simply retrieve song metadata, the [Spotify API](https://developer.spotify.com/dashboard/) could be of interest.
From glancing at the [docs](https://developer.spotify.com/documentation/web-api/reference/), you're able to retrieve track info with a `GET` request to `https://api.spotify.com/v1/tracks/:trackID`, where `trackID` is one of [these](https://developer.spotify.com/documentation/web-api/#spotify-uris-and-ids).

Getting an ID seems to be the only issue though, unless you actually receive one (which is pretty easy with Discord); Spotify URLs — well, those that are embedded by Discord — include the track ID. There's likely another endpoint for searching.

**Comment by cthpw103** [comment]
Spotify support _would_ be something of interest. However, extracting song name & artist from a Youtube video would be good.

**Comment by alecks** [comment]
Yeah. I should probably try emailing someone about it if it isn't actually implemented.

Spotify does actually have a search function (linked to a Go library since the JS implementation is, uh, a mess): https://github.com/zmb3/spotify/blob/master/search.go.

JS implementation: https://github.com/JMPerez/spotify-web-api-js

**Comment by espimarisa** [comment]
Could be a possibility 🤔

**Comment by espimarisa** [comment]
I've been looking into it a lot recently - possibly expect some stuff on the dev branch soon?

**Comment by alecks** [comment]
Someone I was working with just created something to interface with Spotify's API; they didn't actually need to get explicit access to it either. The only issue seems to be getting track IDs, so possibly a command to fetch _extra_ metadata could be considered?

**Comment by espimarisa** [comment]
hmn, possibly

**Comment by alecks** [comment]
Just one part of it lol
![image](https://user-images.githubusercontent.com/24289784/83338568-785b7600-a2bd-11ea-8880-38f53e6689e8.png)

**Comment by espimarisa** [comment]
could be useful

**Comment by espimarisa** [comment]
After taking a bit of a break from the project and coming back to it, I believe I've found a pretty sweet way to implement all of this. Give me some time... 🤔

**Comment by espimarisa** [comment]
As of right now, I'm heavily focused on improving / refactoring the current code. However, I'll push music commands as a priority for one of our next feature releases. We could probably utilise lavalink for the best performance (doing it the old fashioned way with ytdl is slow, spammy, and ugly), but I haven't looked too much into that as I've been focused on refactors & bugs.

It also doesn't help that I'm pretty much the sole contributor to the project right now. Hibiki has and always will be a passion project, so when motivation goes away, it gets tricky to work on something like this.

**Comment by Akouji** [comment]
daijoubu (´⌣`ʃƪ) I hope the best, maybe later that feature will be available.

**Comment by espimarisa** [comment]
shutup bot

**Comment by espimarisa** [comment]
Shutup

Possibly in the next feature update after v3.2.0?

**Comment by cthpw103** [comment]
no

**Comment by espimarisa** [comment]
Moved this to a new issue, #17
