### ISSUE TITLE
[REQ] Locale Support

### ISSUE THREAD

**Issue by espimarisa** [smolespi/Hibiki#13]
## Localisation & Translations
Something I've been eyeing for a while is native localisation / language support.

## **Why?**
I want the project to be universal. The first step to that was going completely open-source. The next step would be to break language barriers. There's also a large amount of foreign Hibiki users who's first language isn't English. Plus, it's another neat thing to show off.

## **How?**
We'd need to make a way to read strings from locale files. I know @TTtie has experience in this - however preferably, we'd want to make it... clean and simple. Less of a total pain to implement. Maybe give me your input?

The actual translations would affect bot content. We'd translate every string sent by Hibiki. While this is *tedious**, IMHO it's well worth it in the future.

Additionally, getting translators for core languages might not be too difficult. I know a few people outside the project who'd be happy to help, and our development team is pretty diverse language-wise (even though I only know English).

Thoughts? Suggestions? Possible implementation ideas?

**Comment by espimarisa** [comment]
All of you bloody ghosted me, thanks. I'll look into this for v3.3.0, but I'd appreciate any feedback @TTtie

**Comment by cthpw103** [comment]
will we have to map every english string to a foreign language or use something like `strings.greetings`?

**Comment by cthpw103** [comment]
good idea though, you could probably guess the language by server region

**Comment by espimarisa** [comment]
Guessing by region's probably not a smart idea as `europe` could mean a bunch of things. Less so if it's something like..Brazil. We could try to do it selectively, and if it does bad we can force English as the default.

Also, that's one of the things I wanna know. I think doing strings.ITEM is the preferred way, and while it's a bit of a work (Hibiki has a lot of strings), once that's done, it's just a matter of translation. 

If the translation doesn't have the string, fall back to the english one.

We're pretty diverse language-wise, so I know we could *probably* get the following languages supported:

- English
- French & French (CA, if there's a big enough difference)
- Czech/Slovak
- Spanish (not sure which exact locale tbh)
- Dutch/NL
- Probably more

**Comment by cthpw103** [comment]
If it's these regions, you could guess it easily
no big difference between Canadian and French french

![image](https://user-images.githubusercontent.com/30247185/93806610-4cd01300-fc41-11ea-9bc1-49092bcaa32a.png)

**Comment by espimarisa** [comment]
Probably shouldn't guess Hong Kong/singapore/south africa and leave them as english as they power a lot more than just that country alone. India would probably be english too. But brazil would be a good guess, we have a lot of users there for some reason.

**Comment by espimarisa** [comment]
nonononono wdkokowkoekfge anjsdwenjk dknjewfkf

**Comment by espimarisa** [comment]
The locale system has been completed for v3.3.0. Hopefully we will have at least three languages - english and french are guaranteed, but we can probably squeeze in a couple more. I'm going to look into asking Crowdin for an Open-Source license to aid locale porting in the future as there aren't any good FOSS alternatives that I know about.

**Comment by Nightlyion** [comment]
> 
> 
> The locale system has been completed for v3.3.0. Hopefully we will have at least three languages - english and french are guaranteed, but we can probably squeeze in a couple more. I'm going to look into asking Crowdin for an Open-Source license to aid locale porting in the future as there aren't any good FOSS alternatives that I know about.

Weblate? However its not FOSS, but it can be self hosted.

**Comment by CrankDatSouljaBoy** [comment]
> not FOSS

https://github.com/WeblateOrg/weblate
seems like a foss program using a foss license
we might consider this, it looks like it's only paid for hosting in their servers, we're already paying for servers,  i don't see why not

**Comment by espimarisa** [comment]
TIL I actually get Crowdin Bronze for a year free thru my GitHub Student Developer pack. While Bronze only gives up to 5000 strings, I think it would be good enough without having to apply for an open-source license thru them.

If it *does* get to that point, then we can do this. I'm going to look into it this evening and I will update (or close) the issue later.

Additionally, the locale system is implemented (almost all of the work was done by @resolvedxd, thank him for being awesome) for v3.3.0. 

![image](https://user-images.githubusercontent.com/49253425/102151157-41574700-3e40-11eb-8102-bb5f08027d95.png)

**Comment by espimarisa** [comment]
We'll be using Crowdin - translate.hibiki.app.

If anyone is interested in translating, DM me on discord at espi#0001 before you do anything.

I will be writing a TRANSLATION.md file when we get closer to v3.3.0 rc and most of the strings have been ported to JSON.

Closing this issue now.
