### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by Jordaar** [smolespi/Hibiki#15]
Hey I was wondering if its possible to run the bot without RethinkDB. 
I don't want the commands that use DB...
 
 Thanks!

**Comment by smolespi** [comment]
Right now, you need rethinkdb for things such as the command handler to work.

However, there's an extremely WIP json provider on the way. 

Eventually, there will be proper db-free support. But right now, you need it.

**Comment by Jordaar** [comment]
okay thanks!
