### ISSUE TITLE
[REQ] Stop using no-cache in the dashboard; implement a proper fix

### ISSUE THREAD

**Issue by espimarisa** [smolespi/Hibiki#21]
# Overview
In order to fix the infinite authentication issue, we introduced the noCache function to disable caching in each route. This fixed the issue, however, having things cached would be nice.

# How?
We should try and find exactly *why* authentication (more specifically, reauthentication, etc) breaks if caching is enabled, and try and implement something more direct and less broad. This isn't a huge deal, but it could help save a teeny bit of bandwidth.

**Comment by TTtie** [comment]
no-cache is the defacto standard for dynamic pages/APIs and therefore this is a wontfix issue to me

**Comment by espimarisa** [comment]
I thought we used it for *everything*. I can't read.
