### ISSUE TITLE
[BUG] Simple Spelling mistake in the wiki of the bot.

### ISSUE THREAD

**Issue by itzvaporwave** [smolespi/Hibiki#5]
**Description**
Under the last paragraph of the 'Hosting Setup' part of the wiki. in the second last sentence, the line features a missing space in "you cansetup the".

**Reproduction**

1. Go to https://github.com/smolespi/Hibiki/wiki/Hosting-Setup in web browser.
2. Navigate to the second last sentence in the last paragraph

**Comment by espimarisa** [comment]
Cheers for pointing this out - I'm in the process of redoing all of the documentation etc. to be **much** nicer and straightforward. Should be fixed for now.
