### ISSUE TITLE
[BUG] h!catgirl invokes h!cat behavior

### ISSUE THREAD

**Issue by Alphadelta14** [smolespi/Hibiki#52]
**Description**
h!catgirl invokes h!cat behavior. h!foxgirl invokes h!fox behavior. Slightly inconsistent (on a server, they happened to work correctly).

**Reproduction**

1. Use catgirl or foxgirl commands

**Expected behavior**
Expected catgirl or foxgirl. Got cat / fox.

**Screenshots**
![image](https://user-images.githubusercontent.com/480845/101719612-ac380500-3a71-11eb-9b6b-2bccdbce9dbf.png)
![image](https://user-images.githubusercontent.com/480845/101719596-a2160680-3a71-11eb-8599-9aa996fd653e.png)

**Additional context**

**Comment by espimarisa** [comment]
this is due to inconsistencies in our command handler, will be patched out in the next release

**Comment by espimarisa** [comment]
fixed
