### ISSUE TITLE
[HELP] I got error when starting with node .

### ISSUE THREAD

**Issue by proudparrot2** [smolespi/hibiki#77]
**Description**
I got this error when starting the bot with `node .` - `Error while starting the database, exiting: ReqlDriverError: Error initializing master pool`. I did `npm install`, but its not working.
**Screenshots**
![Screen Shot 2021-02-02 at 1 55 07 PM](https://user-images.githubusercontent.com/71939973/106654914-51e18f00-655e-11eb-8595-77a1f134cf31.png)

**Additional context**
Is there additional config I need to make? I filled out `config.json`.

**Comment by smolespi** [comment]
You need to have RethinkDB running. 

https://github.com/smolespi/Hibiki/wiki/RethinkDB
